[build]
  command = "cd frontend && npm install && npm run build"
  functions = "netlify/functions"
  publish = "frontend/.next"

[dev]
  command = "cd frontend && npm run dev"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
